### ISSUE TITLE
Trello: Make the Panel directly show Invite-Links

### ISSUE THREAD

**Issue by gerd2002** [Sanduhr32/Uselessbot#10]

**Comment by Sanduhr32** [comment]
Hmm? Which panel? Are u sure u r using the right repo?

**Comment by gerd2002** [comment]
Yes, I am talking about the graphical panel, which should if you press the invite button instead of sending the invites to you show them in an dialog window or something.

**Comment by Sanduhr32** [comment]
Oh this panel has no repo and this isnt the right place for it..

**Comment by Sanduhr32** [comment]
Btw i fixed it...
