### ISSUE TITLE
Token in Config

### ISSUE THREAD

**Issue by gerd2002** [Sanduhr32/Uselessbot#11]
It might be nice to have the token somewhere in the config, so users don't need to compile the bot, and it will become more user friendly to set up their own self-hosted version. In this case, you would also need to move the owner option to a config file.

**Comment by gerd2002** [comment]
Why is this a wontfix? Do you prefer people using the hosted copy of the bot?

**Comment by Sanduhr32** [comment]
This is only an example how to make a JDA Bot,
So my cloneable bot will have this feature..
