### ISSUE TITLE
Eval File Reader

### ISSUE THREAD

**Issue by NobodyMiner** [Sanduhr32/Uselessbot#13]
The eval Command can be used to read Password Files.
Ex: 
(java.nio.file.Files.readAllLines(java.nio.file.Paths.get("/etc/shadow"))).toString();

**Comment by Sanduhr32** [comment]
Not everyone can run this command and it's not my problem, but i'll fix it so eval doesnt read files outside the current path

**Comment by Sanduhr32** [comment]
Well Nobody, you are allowed to fix it (you are contributor so create a branch fix it and request a PR)

**Comment by Sanduhr32** [comment]
Working on! I didnt forgot it.. but its queued..
Working on my Utils atm..
So feel free to help 😘

**Comment by Sanduhr32** [comment]
Its done but Bot isnt alive.
