### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Sanduhr32** [Sanduhr32/Uselessbot#7]
Hey guys,
If you have ideas for my bot here you can post it and i will check and try to add them.
Make a list like:
> ### Ideas
>|  Command  | Description |   Syntax   |
>|  -------  | ----------- |   -----   |
>|  Time  |  Returns the current time from the host  | ??time |

For the embed use ">" at first char, for the table "| TEXT | TEXT | TEXT |" and for the title "### TITLE"
Regards
Sanduhr32

**Comment by gerd2002** [comment]
And for the table line use
|  -------  | ----------- |   -----   |
